"""Focused tests for Python-side MHD finite-volume helpers."""

import unittest

import numpy as np

from quasar.mhd import numerics as mhd_num


def _ring_average_power(r_lo, r_hi, degree):
    """Exact average of ``r**degree`` under ``abs(r) dr`` on one cell."""
    def primitive(radius, power):
        value = radius ** (power + 2) / (power + 2)
        return value if radius >= 0.0 else -value

    volume = primitive(r_hi, 0) - primitive(r_lo, 0)
    moment = primitive(r_hi, degree) - primitive(r_lo, degree)
    return moment / volume


class RadialFaceCollocationTests(unittest.TestCase):

    def test_centered_rows_match_cpp_golden(self):
        # Generated by C++ solve_radial_row with target=cell_average,
        # offset=-width/2, and node_xi=0.5. Keeping literals here makes drift
        # between the independently executed Python and native seed paths loud.
        golden = {
            (4, 0.5): [
                -0.03888888888888889, 0.36666666666666664,
                0.71666666666666667, -0.044444444444444287],
            (6, 0.5): [
                0.0073412698412698412, -0.060317460317460318,
                0.37896825396825395, 0.73492063492063497,
                -0.068849206349206354, 0.0079365079365079083],
            (8, 0.5): [
                -0.0015354938271604939, 0.014931657848324516,
                -0.073614417989417993, 0.38533950617283952,
                0.74433972663139325, -0.08397486772486773,
                0.016136463844797177, -0.0016225749559082292],
            (4, 1.5): [
                -0.040740740740740744, 0.48333333333333334,
                0.59999999999999998, -0.042592592592592515],
            (6, 1.5): [
                0.0075396825396825398, -0.063161375661375668,
                0.49761904761904763, 0.6162698412698413,
                -0.066005291005291011, 0.0077380952380952106],
            (8, 1.5): [
                -0.0015645208700764256, 0.015333259847148737,
                -0.077067901234567901, 0.5050062463256908,
                0.62467298647854208, -0.080521384479717809,
                0.015734861845972958, -0.0015935479129924879],
            (4, 10.0): [
                -0.041527777777777775, 0.53291666666666671,
                0.55041666666666667, -0.041805555555555651],
            (6, 10.0): [
                0.0076240079365079367, -0.064370039682539681,
                0.54804563492063496, 0.56584325396825397,
                -0.064796626984126984, 0.007653769841269864],
            (8, 10.0): [
                -0.0015768573633156966, 0.015503940696649029,
                -0.07853563161375661, 0.55586461089065253,
                0.57381462191358024, -0.0790536541005291,
                0.015564180996472663, -0.0015812114197530924],
        }
        for (width, rho), expected in golden.items():
            with self.subTest(width=width, rho=rho):
                np.testing.assert_allclose(
                    mhd_num._radial_face_to_cell_centered_weights(width, rho),
                    np.asarray(expected, dtype=np.float64),
                    rtol=0.0, atol=3.0 * np.finfo(np.float64).eps)

    def test_centered_rows_recover_ring_average_polynomials(self):
        nghost = 4
        nx = 12
        extent = nx + 2 * nghost
        dr = 0.125
        origin_x = 1.0
        face_r = origin_x + (np.arange(extent) - nghost) * dr
        for degree in range(8):
            values = np.tile(face_r ** degree, (3, 1))
            result = mhd_num.radial_face_samples_to_cell_average(
                values, nghost, origin_x, dr)
            # Width-eight centered stencils exist for q=3..extent-5.
            for q in range(3, extent - 4):
                r_lo = origin_x + (q - nghost) * dr
                expected = _ring_average_power(r_lo, r_lo + dr, degree)
                self.assertAlmostEqual(
                    result[1, q], expected, places=11,
                    msg=f"degree={degree}, q={q}")

    def test_mp5_width_is_independent_of_an_overpadded_halo(self):
        nghost = 4
        nx = 12
        extent = nx + 2 * nghost
        dr = 0.125
        origin_x = 1.0
        face_r = origin_x + (np.arange(extent) - nghost) * dr
        for degree in range(6):
            values = np.tile(face_r ** degree, (2, 1))
            result = mhd_num.radial_face_samples_to_cell_average(
                values, nghost, origin_x, dr, scheme_order=5)
            # A six-point MP5 row starts two slots to the left of its target.
            for q in range(2, extent - 3):
                r_lo = origin_x + (q - nghost) * dr
                expected = _ring_average_power(r_lo, r_lo + dr, degree)
                self.assertAlmostEqual(
                    result[0, q], expected, places=11,
                    msg=f"degree={degree}, q={q}")

    def test_muscl_width_is_independent_of_an_overpadded_halo(self):
        nghost = 4
        nx = 12
        extent = nx + 2 * nghost
        dr = 0.125
        origin_x = 1.0
        face_r = origin_x + (np.arange(extent) - nghost) * dr
        for degree in range(4):
            values = np.tile(face_r ** degree, (2, 1))
            result = mhd_num.radial_face_samples_to_cell_average(
                values, nghost, origin_x, dr, scheme_order=2)
            for q in range(1, extent - 2):
                r_lo = origin_x + (q - nghost) * dr
                expected = _ring_average_power(r_lo, r_lo + dr, degree)
                self.assertAlmostEqual(result[0, q], expected, places=11)

    def test_one_sided_closure_folds_radius_into_gauss_weights(self):
        nghost = 4
        nx = 12
        extent = nx + 2 * nghost
        dr = 0.125
        origin_x = 1.0
        face_r = origin_x + (np.arange(extent) - nghost) * dr
        # Four-point Gauss integration remains exact through degree six in the
        # sampled polynomial after multiplication by the linear radial metric.
        for degree in range(7):
            values = np.tile(face_r ** degree, (2, 1))
            result = mhd_num.radial_face_samples_to_cell_average(
                values, nghost, origin_x, dr)
            for q in (0, 1, 2, extent - 4, extent - 3, extent - 2, extent - 1):
                r_lo = origin_x + (q - nghost) * dr
                expected = _ring_average_power(r_lo, r_lo + dr, degree)
                self.assertAlmostEqual(
                    result[0, q], expected, places=11,
                    msg=f"degree={degree}, q={q}")

    def test_overpadded_mp5_one_sided_closure_uses_six_points(self):
        nghost = 4
        nx = 12
        extent = nx + 2 * nghost
        dr = 0.125
        origin_x = 1.0
        face_r = origin_x + (np.arange(extent) - nghost) * dr
        for degree in range(6):
            values = np.tile(face_r ** degree, (2, 1))
            result = mhd_num.radial_face_samples_to_cell_average(
                values, nghost, origin_x, dr, scheme_order=5)
            for q in (0, 1, extent - 3, extent - 2, extent - 1):
                r_lo = origin_x + (q - nghost) * dr
                expected = _ring_average_power(r_lo, r_lo + dr, degree)
                self.assertAlmostEqual(
                    result[0, q], expected, places=11,
                    msg=f"degree={degree}, q={q}")

    def test_axis_ghost_cells_use_absolute_radius_measure(self):
        nghost = 4
        nx = 12
        extent = nx + 2 * nghost
        dr = 0.25
        face_r = (np.arange(extent) - nghost) * dr
        values = np.tile(face_r ** 3, (2, 1))
        result = mhd_num.radial_face_samples_to_cell_average(
            values, nghost, origin_x=0.0, dr=dr)
        for q in range(3, extent - 4):
            r_lo = (q - nghost) * dr
            expected = _ring_average_power(r_lo, r_lo + dr, 3)
            self.assertAlmostEqual(result[0, q], expected, places=12)

    def test_rejects_a_cell_that_straddles_the_axis(self):
        with self.assertRaisesRegex(ValueError, "straddle"):
            mhd_num.radial_face_samples_to_cell_average(
                np.ones((2, 10)), nghost=2, origin_x=0.25, dr=1.0)

    def test_rejects_invalid_scheme_order(self):
        values = np.ones((2, 12))
        for invalid in (True, 1, 6, 5.5, "mp5", np.nan):
            with self.subTest(scheme_order=invalid):
                with self.assertRaisesRegex(ValueError, "scheme_order"):
                    mhd_num.radial_face_samples_to_cell_average(
                        values, nghost=2, origin_x=1.0, dr=0.1,
                        scheme_order=invalid)

    def test_rejects_extent_smaller_than_explicit_scheme_stencil(self):
        with self.assertRaisesRegex(ValueError, "smaller"):
            mhd_num.radial_face_samples_to_cell_average(
                np.ones((2, 6)), nghost=1, origin_x=1.0, dr=0.1,
                scheme_order=7)


if __name__ == "__main__":
    unittest.main()
